# This file and everything in its directory are copied to $KETL_OUT/tmp/knet-init/config 
# by neo-indexing.sh, and merged there with files coming from KNET_HOME/datasets
#
# The relative paths used here work from that resulting dir.

"@includes":
- config-neo4j.yml

# For the tests, we have to use this OXL, which overrides the defaults loaded above
#
dataDir: "${KETL_OUT}/tmp/knet-init/data"
oxl: "" # overridden by commands

customOptions @merge:
  cypherConceptIndexProps: "${mydir}/neo4j/concept-index-properties.txt"
