language: java
jdk: openjdk8

install: echo "Skipping default installation step"

before_script:
  - echo -e "\n\n\tInitialising test resources (data server etc)\n"
  - ./resources-init.sh
      
script: 
  - mvn deploy --settings settings.xml

after_script:
  - echo -e "\n\n\tTerminating test resources\n"
  - ./resources-shutdown.sh
  
cache:
  directories:
    - $HOME/.m2
  
