jobs: 16
cluster: "sbatch --chdir=/home/data/knetminer/software/knetminer-backend/rres-endpoints --mem=65g --qos=long --time=1-0:0:0  -o .snakemake/log/slurm-{rule}-{wildcards}.out -e .snakemake/log/slurm-{rule}-{wildcards}.out"
