jobs: 16
cluster: "sbatch --chdir=/home/data/knetminer/software/knetminer-backend/rres-endpoints --mem=500g --cpus-per-task=16 --qos=long --time=1-0:0:0  -o .snakemake/log/slurm-{rule}.out -e .snakemake/log/slurm-{rule}.out"
