# These files are passed to the Ondex Metadata descriptor tool.
# https://github.com/Rothamsted/knetbuilder/tree/master/ondex-knet-builder/modules/rdf-export-2
#
datasetId = brassicaceae-premium
datasetAccession = KnetMiner:Brassicaceae
datasetTitle = Knetminer's knowledge graph about brassicas
datasetDescription = \
  Knetminer is a gene discovery platform, which allows for exploring knowledge graphs computed \
  from common plant biology data, such as ENSEMBL, UniProt, TAIR, PUBMED and more.\n\
	The brassicaceae dataset contains information about 6 brassica species, which is also linked \
	to embedded data about the Arabidopsis thaliana model organism.\n\
	This edition includes Brassica juncea, Brassica napus, Brassica oleracea, Brassica oleracea var. botrytis (cauliflower), Brassica rapa R-o-18, Camelina sativa.
datasetVersion = 63
# TODO: better URLs
datasetURL = https://knetminer.com/about
datasetNeo4jBrowserURL = <http://localhost:7474>
datasetNeo4jBOLTURL = <bolt://localhost:7687>
