# These files are passed to the Ondex Metadata descriptor tool.
# https://github.com/Rothamsted/knetbuilder/tree/master/ondex-knet-builder/modules/rdf-export-2
# 
datasetId = fungi-premium
datasetAccession = KnetMiner:Fungi
datasetTitle = Knetminer's knowledge graph about fungi
datasetDescription = \
  Knetminer is a gene discovery platform, which allows for exploring knwoledge graphs computed \
  from common plant biology data, such as ENSEMBL, UniProt, TAIR, PUBMED and more.\n\
	The fungi dataset contains information about the 14 fungi species, which is also linked \
	to embedded data about the Yeast model organism.\n\
	This edition includes Saccharomyces cerevisiae, Aspergillus fumigatus, Aspergillus_nidulans, Candida_albicans, Fusarium_culmorum, Fusarium_graminearum, Magnaporthe_oryzae, Neurospora_crassa, Schizosaccharomyces_pombe, Zymoseptoria_tritici, Fusarium odoratissimum, Fusarium oxysporum lycopersici, Fusarium oxysporum Fo47, Verticillium dahliae.
datasetVersion = 63
# TODO: better URLs
datasetURL = https://knetminer.com/about
datasetNeo4jBrowserURL = <http://localhost:7474>
datasetNeo4jBOLTURL = <bolt://localhost:7687>
